- id: '1548198837595'
  alias: Besoin d'eau
  trigger:
  - above: '60'
    below: '20'
    entity_id: sensor.miflora_moisture
    platform: numeric_state
  condition: []
  action:
  - alias: ''
    data:
      message: Yucca à soif
      title: Yucca à soif
    service: persistent_notification.create
