- platform: rflink
  automatic_add: false
  devices:
    fineoffset_003d_bat:
      name: Batterie chambre Soline
      sensor_type: battery
    fineoffset_003d_temp:
      name: Temperature chambre Soline
      sensor_type: temperature
    fineoffset_003d_hum:
      name: Humidité chambre Soline
      sensor_type: humidity
    fineoffset_005b_bat:
      name: Batterie bureau Dimitri
      sensor_type: battery
    fineoffset_005b_temp:
      name: Temperature bureau Dimitri
      sensor_type: temperature
    fineoffset_005b_hum:
      name: Humidité bureau Dimitri
      sensor_type: humidity
    fineoffset_001d_bat:
      name: batterie chambre Parentale
      sensor_type: battery
    fineoffset_001d_temp:
      name: Temperature chambre Parentale
      sensor_type: temperature
    fineoffset_001d_hum:
      name: Humidité chambre Parentale
      sensor_type: humidity
    inovalley_fc01_bat:
      name: batterie Salon
      sensor_type: battery
    inovalley_fc01_temp:
      name: Temperature Salon
      sensor_type: temperature
    inovalley_fc01_hum:
      name: Humidité Salon
      sensor_type: humidity
    wh3_46e0_temp:
      name: Temperature Salle de bain
      sensor_type: temperature
    wh3_46e0_hum:
      name: Humidité Salle de bain
      sensor_type: humidity
    wh3_4490_temp:
      name: Temperature alcôve
      sensor_type: temperature
    wh3_4490_hum:
      name: Humidité alcôve
      sensor_type: humidity
    wh3_4c90_temp:
      name: Temperature Chambre d'amis
      sensor_type: temperature
    wh3_4c90_hum:
      name: Humidité Chambre d'amis
      sensor_type: humidity


- platform: linky
  username: !secret linky_username
  password: !secret linky_password
  peak_hours:
     - ["00:00","23:59"]
  peak_hours_cost: 0.09429
  offpeak_hours_cost: 0.09429


- platform: miflora
  mac: 'C4:7C:8D:6A:04:0D'
  name: miflora
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

